version: "3.6"
services:
    nodeapp:
        container_name: nodeapp
        build:
            context: .
            dockerfile: Dockerfile
        image: nodeapp:0.0.1
        ports:
            - 4200:4200
        networks:
            - common
        links:
            - mongodb
        volumes:
            - ./:/usr/src/app
        environment:
            PORT: 4200
            MONGOURI: "mongodb://mongodb/node-mvc"
            NODE_ENV: "dev"
        command: npm start
    mongodb:
        container_name: mongodb
        image: mongo:4.2.17-bionic
        ports:
            - 8080:27017
        volumes:
            - ./data/mongodb:/data/db
        networks:
            - common
volumes:
    mongodb:
        external: true
    mongoconfig:
    nodeapp:
        external: true
networks:
    common:
